### ISSUE TITLE
Store the data in Hyperspecialize, not the target module

### ISSUE THREAD

**Issue by peterahrens** [peterahrens/Hyperspecialize.jl#6]
The first pass on this package was a little fast and one of the things that happened is that data was stored in the target modules. It would be better if we were more explicit about calling our widens during `__init__()`.

**Comment by willow-ahrens** [comment]
I think this is a bad idea now.

**Comment by willow-ahrens** [comment]
Its a bad idea because it means that you can't precompile local hyperspecializations.
